name: Frontend CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'Front/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js (without caching)
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          # Видаляємо cache параметр

      - name: Install dependencies
        run: npm ci
        working-directory: Front

      - name: Build application
        run: npm run build
        working-directory: Front

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            set -euxo pipefail
            
            cd /opt/app/Front
            
            # Встановлюємо залежності без кешу
            npm ci --no-audit --prefer-offline
            
            # Будуємо проект
            npm run build
            
            # Копіюємо збірку
            sudo mkdir -p /opt/app/frontend-build
            sudo cp -r dist/* /opt/app/frontend-build/
            
            # Перезапускаємо nginx
            cd /opt/app
            docker compose restart nginx
            
            echo "🚀 Deployment successful!"
            echo "📦 Build files copied to /opt/app/frontend-build"
