name: Frontend Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            set -euxo pipefail
            
            # Переходимо в директорію проекту
            cd /opt/app
            
            # Оновлюємо код
            git pull origin main
            
            # Встановлюємо залежності та будуємо фронтенд
            cd Front
            npm ci
            npm run build
            
            # Перезапускаємо nginx
            cd /opt/app
            docker compose restart nginx
            
            echo "✅ Frontend deployed successfully!"
