name: Frontend CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'Front/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: Front/package-lock.json

      - name: Install dependencies and build
        run: |
          npm ci
          npm run build
        working-directory: Front

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            set -euxo pipefail
            
            cd /opt/app
            git pull origin main
            
            cd Front
            npm ci
            npm run build
            
            sudo mkdir -p /opt/app/frontend-build
            sudo cp -r dist/* /opt/app/frontend-build/
            
            cd /opt/app
            docker compose restart nginx || docker compose up -d
            
            echo "Deployment completed successfully!"
            docker compose ps
