name: Frontend Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies and build
        run: |
          cd Front
          npm ci
          npm run build
        env:
          VITE_API_URL: https://beez.pp.ua/api

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            set -euxo pipefail
            
            cd /opt/app
            
            git pull origin main
            
            rsync -av --delete Front/dist/ /opt/app/Front/dist/
            
            cd /opt/app
            docker-compose restart frontend nginx
            
            echo "Frontend deployed successfully!"
